#!/usr/bin/env bash
# install nginx on a server
sudo apt-get update -y;
sudo apt-get install nginx -y;
sudo ufw allow 'Nginx HTTP';
printf 'server {
    listen 80;
    location / {
        return 200 "Hello World!\n";
        add_header ETag $upstream_http_etag;
        add_header Accept-Ranges $upstream_http_accept_ranges;
    }
}\n' | sudo tee /etc/nginx/sites-available/hello_world;
if [ -L /etc/nginx/sites-enabled/hello_world ]; then
    sudo rm /etc/nginx/sites-enabled/hello_world;
fi
sudo ln -s /etc/nginx/sites-available/hello_world /etc/nginx/sites-enabled/;
sudo service nginx restart;
sudo nginx -t;