#!/usr/bin/env bash
# install nginx on a server
sudo apt-get update -y;
sudo apt-get install nginx -y;
sudo rm /etc/nginx/sites-enabled/default;
printf 'server {
    listen 80;
    location / {
        return 200 "Hello World!\n";
    }
}\n' | sudo tee /etc/nginx/sites-available/hello_world;
sudo ln -s /etc/nginx/sites-available/hello_world /etc/nginx/sites-enabled/;
sudo service nginx restart;
sudo nginx -t;