#!/usr/bin/env bash
# install nginx on a server
sudo apt-get update -y;
sudo apt-get install nginx -y;
sudo ufw allow 'Nginx HTTP';
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html;
printf "server {
    listen 80;
    location / {
        return 200 \"%s\\n\";
        add_header ETag \$upstream_http_etag;
        add_header Accept-Ranges \$upstream_http_accept_ranges;
    }
    location = /redirect_me {
        return 301 http://shvmpz.tech/new_page;
    }
    error_page 404 /usr/share/nginx/html/custom_404.html;
    location = /usr/share/nginx/html/custom_404.html {
        internal;
    }
}\n" "Hello World!" | sudo tee /etc/nginx/sites-available/hello_world;
if [ -L /etc/nginx/sites-enabled/hello_world ]; then
    sudo rm /etc/nginx/sites-enabled/hello_world;
fi
sudo ln -s /etc/nginx/sites-available/hello_world /etc/nginx/sites-enabled/;
sudo service nginx restart;
sudo nginx -t;